### ISSUE TITLE
ColouredChat breaks Quark's Item Linking feature

### ISSUE THREAD

**Issue by comp500** [Pxl-8/ColouredChat#1] opened 2019-08-15 23:37 UTC
ColouredChat 1.12.2-0.3.1
Quark r1.6-177
Forge 14.23.5.2838

When pressing Shift+T, the item name appears in the chat, but the item image does not appear, and the tooltip of the item does not work.

![image](https://user-images.githubusercontent.com/1138417/63133604-e7c9d880-bfbd-11e9-9b08-2489701dbd6d.png)

**Comment by uberifix** [comment] 2019-08-16 01:53
Unfortunately the issue is a bit advanced and will require some time and rewriting to solve, which at this point in time I have no estimates as to how long it will take.

Is this an urgent matter for you? I have a bit of a quick hacky fix at the moment which should work

![image](https://uberi.fi/x/GammaCabeiriQFv)

**Comment by comp500** [comment] 2019-08-16 10:05
It's not an urgent matter for me, I can see how it would be difficult! Don't worry too much if you can't get it to work, it's not that big a feature of Quark.

Thanks for the impressively quick response!

**Comment by uberifix** [comment] 2019-11-27 04:26
Unfortunately a bit of a late response as I was only recently able to test Quark on 1.14, but this issue no longer exists in 1.14 with the new way i implemented the name colouring. 

I also just released a backport of the 1.14 code to 1.12 so this issue should also be resolved in 1.12 with the 1.12.2-1.4.0 update.

**Closed as completed** 2019-11-27 04:27 UTC
Labels: bug
